{% set name = "eventlet" %}
{% set version = "0.31.0" %}
{% set sha256 = "b36ec2ecc003de87fc87b93197d77fea528aa0f9204a34fdf3b2f8d0f01e017b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python
    - greenlet >=0.3
    - enum34  # [py<34]
    - dnspython >=1.15.0
    - monotonic >=1.4
    - six >=1.10.0
    - pyopenssl

test:
  imports:
    - eventlet
    - eventlet.green
    - eventlet.green.OpenSSL
    - eventlet.green.http  # [py3k]
    - eventlet.green.urllib
    - eventlet.greenio
    - eventlet.hubs
    - eventlet.support

about:
  home: http://eventlet.net
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Highly concurrent networking library

